import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "夏小雨 8 的系统",
  description: "Generated by xiaxiaoyu8",
  icons: {
    icon: "/favicon.ico", // 指向 public 目录下的文件，或者 Next.js 会自动处理 app/ 目录下的
                          // 如果您将 favicon.ico 放在 app/ 目录下，通常不需要显式指定
                          // 如果您用的是 app/icon.png, 可以写 icon: '/icon.png' (Next.js会处理)
                          // 或者提供一个位于 public 目录的路径
    // apple: "/apple-icon.png", // 示例：为苹果设备指定图标
    // shortcut: "/shortcut-icon.png" // 示例：快捷方式图标
  },
};

// ... rest of the layout component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
